### PR TITLE
Migration to the angular 4 package format with filipesilva/angular-qu…

### PR DESCRIPTION
**Pull request by JulienBourgain**
…ickstart-lib

I have just take the angular-quickstart-lib repo and removed the demo folder
then I put your code in the src/lib folders
then I modified your code to pass the build and test phase (just add some rxjs imports and explicit the import frmo "module/index" and "service/index"

### CODE REVIEW

**Comment by serhiisol** [comment]
Not sure what you're trying to achieve here, but this repo is the library for angular2+, it's used to help you solve problems with missing interceptor functionality, it doesn't provide any app skeletons or structures.

**Comment by JulienBourgain** [comment]
It's a structure for the library which provide bundle the library to publish it on npm

**Comment by serhiisol** [comment]
Not sure that I understood everything, still package is already published on NPM, besides that, there are a lot of changes must be done to this PR first. E.g. README must be adjusted first, etc.

**Comment by JulienBourgain** [comment]
Ok, I fork your lib, and stabilize that with some other modifications

**Pull request closed without merging**
